services:
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
      target: base
    container_name: client
    ports:
      - 3000:3000 
      - 5173:5173
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/public
      - /app/src
    
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:5171
    depends_on:
      - server
  server:
    build: ./server
    container_name: server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
      - /app/public
      - /app/src
    environment:
      - ATLAS_URI=mongodb://root:example@mongodb:27017/my_db?authSource=admin
      - NODE_ENV=development
      - PORT=5000
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./volumes/data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_INITDB_DATABASE=my_db
